apiVersion: v1
kind: Service
metadata:
  name: retrodiner-service
spec:
  type: LoadBalancer
  selector:
    app: retrodiner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
